# SITE CONFIGURATION
title: 이 재 현  # your site title
author: hjl101076 # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://hjl101076.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Skills & About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline:
 >
  방문해주셔서 감사합니다. 컴퓨터 공학 석사 이재현입니다. 
>
   2016~2018 : 중앙대학교 컴퓨터 공학부 졸업
   2018~2020 : 중앙대학교 대학원 졸업
            - 컴퓨터 공학부 응용 소프트웨어학과 석사 학위
            - 컴퓨터 그래픽스 학회 논문 : 대화형 가상 현실에서 아바타의 립싱크(DOI:10.15701/kcgs.2020.26.4.9)
            - 가상현실(VR) 사용자 상체 추정 및 얼굴 동기화
>
  2020~현재 : 통합 시스템 개발
            - GIS 기반 솔류션 및 하이브리드 앱(Cordova) 개발
            - 공공기관(서울특별시청, 대한민국 환경부, 국토교통부, 한국수자원공사) 업무 관련 시스템 개발
            - egovframework, Spring Boot 개발
            - Restful API 시스템 개발 및 운영
            - RDBMS(PostgreSQL,Oracle,MariaDB) 운영
            - SVN,GIT 버전 및 Maven,Gradle 프로젝트 관리
            - Flutter 앱 개발

          



hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: hjl101076@naver.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: hjl101076 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
